[package]
name = "v4l"
description = "Safe video4linux (v4l) bindings"
version = "0.13.1"
authors = ["Christopher N. Hesse <raymanfx@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository= "https://github.com/raymanfx/libv4l-rs"

[dependencies]
bitflags = "1.2.1"
libc = "0.2"
v4l-sys = { path = "v4l-sys", version = "0.2.0", optional = true }
v4l2-sys = { path = "v4l2-sys", version = "0.2.0", package="v4l2-sys-mit", optional = true }
v4l2-sys-vendored = { path = "v4l2-sys-vendored", version = "0.1.0", optional = true }

[dev-dependencies]
glium = "0.27.0"
jpeg-decoder = "0.2.1"

[features]
default = ["v4l2"]
libv4l = ["v4l-sys"]
v4l2 = ["v4l2-sys"]
vendored = ["v4l2-sys-vendored"]

[workspace]
members = [
    "v4l-sys",
    "v4l2-sys",
    "v4l2-sys-vendored"
]
